language: java
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.m2
matrix:
  include:
    - stage: test
    - stage: publish
      sudo: required
      services:
      - docker
      script: ./.travis.docker-push.sh
stages:
  - test
  - name: publish
    if: branch = master AND type = push
